# Aktualisierte Konfigurationsdatei für Continual-Learning-Benchmark

# Test-Typ: 'replay' oder 'no_replay'
test_type: no_replay

# Modell-Definition
model_module: SoftCon  # Options: 'SpectralGPT' or 'SoftCon'

# Parameter für die Tests
params:
  countries:
    - Finland
    - Ireland
    - Serbia
    - Portugal
  permutation: [0, 1, 2, 3]                # Reihenfolge der Länder-Indices

  # Anzahl der zufällig gezogenen Samples pro Land
  train_samples: 5000 #22482
  test_samples: 500 #8176
  seed: 42                              # Seed für Reproduzierbarkeit

  # DataLoader-Parameter
  batch_size: 64
  num_workers: 4
  epoch: 30
  lr: 1e-4


  # Bildgröße und Filteroptionen
  include_snowy: false
  include_cloudy: false


  save_dir: ./saved_models                # Verzeichnis zum Speichern der Modelle
  log_every_step: true

