# Aktualisierte Konfigurationsdatei für Continual-Learning-Benchmark

# Test-Typ: 'replay' oder 'no_replay'
test_type: no_replay

# Modell-Definition
model_module: SpectralGPT  # Options: 'SpectralGPT' or 'SoftCon'

# Parameter für die Tests
params:
  countries:
    - Finland
    - Ireland
    - Serbia
    - Portugal
  permutation: [0, 1, 2, 3]                # Reihenfolge der Länder-Indices

  # Anzahl der zufällig gezogenen Samples pro Land
  train_samples: 5000 #22482
  test_samples: 500 #8176
  seed: 42                              # Seed für Reproduzierbarkeit

  # DataLoader-Parameter
  batch_size: 16
  num_workers: 4
  epoch: 20
  lr: 1e-4

  # Bildgröße und Filteroptionen
  include_snowy: false
  include_cloudy: false

  # LoRA rank parameter
  r: 16  # Default rank for LoRA

  save_dir: /faststorage/continual_low_rank_adaptation_of_remote_sensing_foundation_models/SpectralGPT/task_tuning/saved_models/rank16              # Verzeichnis zum Speichern der Modelle
  log_every_step: true

